-- Pure rollback SQL; fixture users, templates, projects and tasks never persist.
begin;
create temporary table connect_test_results(message text primary key, passed boolean not null) on commit drop;
create temporary table connect_test_calls(name text primary key, project_id uuid, tasks_assigned integer, tasks_generated integer) on commit drop;
grant select, insert on connect_test_results, connect_test_calls to authenticated;
create function pg_temp.check(ok boolean, message text) returns text language plpgsql as $$
begin
  if ok is distinct from true then raise exception 'FAIL: %', message; end if;
  insert into connect_test_results values(message, true);
  return 'PASS: ' || message;
end $$;
create function pg_temp.reject(command text, expected text, message text) returns text language plpgsql as $$
declare actual text;
begin
  begin execute command; exception when others then get stacked diagnostics actual = returned_sqlstate; end;
  return pg_temp.check(actual = expected, message || coalesce(' (SQLSTATE ' || actual || ')', ' (no error)'));
end $$;
insert into auth.users(id, email, raw_user_meta_data) values
  ('91000000-0000-4000-8000-000000000001', 'connect-owner@example.test', '{}'),
  ('91000000-0000-4000-8000-000000000002', 'connect-admin@example.test', '{}'),
  ('91000000-0000-4000-8000-000000000003', 'connect-member@example.test', '{}'),
  ('91000000-0000-4000-8000-000000000004', 'connect-outsider@example.test', '{}');
insert into public.organizations(id, name, slug) values
  ('92000000-0000-4000-8000-000000000001', 'Connect test A', 'connect-test-a'),
  ('92000000-0000-4000-8000-000000000002', 'Connect test B', 'connect-test-b');
insert into public.organization_members(organization_id, user_id, role) values
  ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000001', 'owner'),
  ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000002', 'admin'),
  ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000003', 'member'),
  ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000004', 'owner');
insert into public.service_templates(id, organization_id, code, name) values
  ('93000000-0000-4000-8000-000000000004', '92000000-0000-4000-8000-000000000002', 'foreign', 'Foreign service');
insert into public.clients(id, organization_id, name, slug) values
  ('97000000-0000-4000-8000-000000000004', '92000000-0000-4000-8000-000000000002', 'Foreign client', 'connect-foreign-client');
set local role authenticated;
select set_config('request.jwt.claim.sub', '91000000-0000-4000-8000-000000000001', true);
insert into public.service_templates(id, organization_id, code, name) values
  ('93000000-0000-4000-8000-000000000001', '92000000-0000-4000-8000-000000000001', 'seo', 'SEO'),
  ('93000000-0000-4000-8000-000000000002', '92000000-0000-4000-8000-000000000001', 'lsa', 'LSA'),
  ('93000000-0000-4000-8000-000000000003', '92000000-0000-4000-8000-000000000001', 'google-ads', 'Google Ads');
insert into public.service_deliverables(id, organization_id, service_template_id, code, name, cadence, target_min, target_max, unit) values
  ('94000000-0000-4000-8000-000000000001', '92000000-0000-4000-8000-000000000001', '93000000-0000-4000-8000-000000000001', 'monthly', 'SEO reporting', 'monthly', 2, 4, 'reports'),
  ('94000000-0000-4000-8000-000000000002', '92000000-0000-4000-8000-000000000001', '93000000-0000-4000-8000-000000000001', 'weekly', 'SEO review', 'weekly', 1, 1, 'review'),
  ('94000000-0000-4000-8000-000000000003', '92000000-0000-4000-8000-000000000001', '93000000-0000-4000-8000-000000000002', 'monthly', 'LSA reporting', 'monthly', 1, 1, 'report');
insert into public.clients(id, organization_id, name, slug) values
  ('97000000-0000-4000-8000-000000000001', '92000000-0000-4000-8000-000000000001', 'Client A', 'connect-client-a'),
  ('97000000-0000-4000-8000-000000000002', '92000000-0000-4000-8000-000000000001', 'Client B', 'connect-client-b'),
  ('97000000-0000-4000-8000-000000000003', '92000000-0000-4000-8000-000000000001', 'Client C', 'connect-client-c');
-- Another active client's missing work must not be generated by connecting A.
insert into public.projects(id, organization_id, client_id, service_template_id, name, status, created_by) values
  ('95000000-0000-4000-8000-000000000001', '92000000-0000-4000-8000-000000000001', '97000000-0000-4000-8000-000000000002', '93000000-0000-4000-8000-000000000001', 'Client B SEO', 'active', auth.uid()),
  ('95000000-0000-4000-8000-000000000002', '92000000-0000-4000-8000-000000000001', '97000000-0000-4000-8000-000000000003', '93000000-0000-4000-8000-000000000002', 'Custom paused LSA name', 'on_hold', auth.uid());
insert into public.tasks(id, organization_id, project_id, client_id, title, status, period_start, period_end, created_by) values
  ('96000000-0000-4000-8000-000000000001', '92000000-0000-4000-8000-000000000001', '95000000-0000-4000-8000-000000000002', '97000000-0000-4000-8000-000000000003', 'Paused historical work', 'todo', (now() at time zone 'Africa/Johannesburg')::date - 20, (now() at time zone 'Africa/Johannesburg')::date - 1, auth.uid()),
  ('96000000-0000-4000-8000-000000000002', '92000000-0000-4000-8000-000000000001', '95000000-0000-4000-8000-000000000002', '97000000-0000-4000-8000-000000000003', 'Paused current one-off', 'todo', null, null, auth.uid());
insert into public.task_assignees(organization_id, task_id, user_id) values
  ('92000000-0000-4000-8000-000000000001', '96000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000001'),
  ('92000000-0000-4000-8000-000000000001', '96000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000001');
create temporary table connect_test_snapshots on commit drop as
  select 'task' kind, t.id, to_jsonb(t) value from public.tasks t where t.organization_id = '92000000-0000-4000-8000-000000000001'
  union all select 'project', p.id, to_jsonb(p) from public.projects p where p.organization_id = '92000000-0000-4000-8000-000000000001';
grant select on connect_test_snapshots to authenticated;

insert into connect_test_calls select 'first', r.* from public.connect_client_service('92000000-0000-4000-8000-000000000001', '97000000-0000-4000-8000-000000000001', '93000000-0000-4000-8000-000000000001', array['91000000-0000-4000-8000-000000000002','91000000-0000-4000-8000-000000000003']::uuid[]) r;
select pg_temp.check((select tasks_assigned = 2 and tasks_generated = 2 from connect_test_calls where name = 'first'), 'connect creates and assigns both current service occurrences');
select pg_temp.check((select p.name = 'SEO' and p.status = 'active' and p.client_id = '97000000-0000-4000-8000-000000000001' and p.service_template_id = '93000000-0000-4000-8000-000000000001' from public.projects p join connect_test_calls c on c.project_id = p.id where c.name = 'first'), 'service template becomes the correct client project');
select pg_temp.check((select count(*) from public.task_assignees a join connect_test_calls c on c.project_id = (select t.project_id from public.tasks t where t.id = a.task_id) where c.name = 'first') = 4, 'both newly generated tasks inherit the selected group immediately');
select pg_temp.check((select count(*) from public.service_assignment_members m join connect_test_calls c on c.project_id = m.project_id where c.name = 'first') = 2, 'service team persists as future default');
select pg_temp.check(not exists(select 1 from public.tasks t join public.service_deliverables d on d.id = t.deliverable_definition_id join connect_test_calls c on c.project_id = t.project_id where c.name = 'first' and (t.target_min <> d.target_min or t.target_max <> d.target_max or t.target_unit <> d.unit or t.period_start <> t.contract_start or t.period_end <> t.contract_end or t.due_date <> t.period_end)), 'generated work preserves full contractual targets and delivery periods');
select pg_temp.check((select count(*) from public.tasks where project_id = '95000000-0000-4000-8000-000000000001') = 0, 'connecting A does not generate missing work for client B');
select pg_temp.check((select count(*) from public.service_assignment_rules where project_id = '95000000-0000-4000-8000-000000000001') = 0, 'another client sharing template keeps its defaults unchanged');
select pg_temp.check(not exists(select 1 from public.projects p join connect_test_snapshots s on s.kind = 'project' and s.id = p.id where to_jsonb(p) is distinct from s.value), 'existing client projects retain every field');

insert into connect_test_calls select 'repeat', r.* from public.connect_client_service('92000000-0000-4000-8000-000000000001', '97000000-0000-4000-8000-000000000001', '93000000-0000-4000-8000-000000000001', array['91000000-0000-4000-8000-000000000002','91000000-0000-4000-8000-000000000003']::uuid[]) r;
select pg_temp.check((select c.project_id = f.project_id and c.tasks_assigned = 2 and c.tasks_generated = 0 from connect_test_calls c join connect_test_calls f on f.name = 'first' where c.name = 'repeat'), 'repeat connection reuses project without duplicate occurrences');
select pg_temp.check((select count(*) from public.projects where client_id = '97000000-0000-4000-8000-000000000001' and service_template_id = '93000000-0000-4000-8000-000000000001') = 1, 'client service uniqueness is preserved');
select pg_temp.check(public.generate_service_deliverables('92000000-0000-4000-8000-000000000001', (select project_id from connect_test_calls where name = 'first')) = 0, 'scoped generator is idempotent');
delete from public.tasks where project_id = (select project_id from connect_test_calls where name = 'first') and deliverable_definition_id = '94000000-0000-4000-8000-000000000002';
-- Simulate missing fixture data for inheritance, not a user-requested deletion.
-- Clear only this synthetic organization's markers inside the rollback test.
reset role;
delete from private.deleted_task_occurrences
  where organization_id = '92000000-0000-4000-8000-000000000001';
set local role authenticated;
select pg_temp.check(public.generate_service_deliverables('92000000-0000-4000-8000-000000000001', (select project_id from connect_test_calls where name = 'first')) = 1, 'scoped generator restores only missing selected weekly occurrence');
select pg_temp.check((select count(*) from public.task_assignees a join public.tasks t on t.id = a.task_id where t.project_id = (select project_id from connect_test_calls where name = 'first') and t.deliverable_definition_id = '94000000-0000-4000-8000-000000000002') = 2, 'regenerated scoped weekly work inherits future team');

insert into connect_test_calls select 'paused', r.* from public.connect_client_service('92000000-0000-4000-8000-000000000001', '97000000-0000-4000-8000-000000000003', '93000000-0000-4000-8000-000000000002', array['91000000-0000-4000-8000-000000000003']::uuid[]) r;
select pg_temp.check((select project_id = '95000000-0000-4000-8000-000000000002' and tasks_assigned = 1 and tasks_generated = 0 from connect_test_calls where name = 'paused'), 'paused existing link saves eligible assignments without generation');
select pg_temp.check((select name = 'Custom paused LSA name' and status = 'on_hold' from public.projects where id = '95000000-0000-4000-8000-000000000002'), 'reconnecting never renames or reactivates paused service');
select pg_temp.check((select user_id from public.task_assignees where task_id = '96000000-0000-4000-8000-000000000001') = '91000000-0000-4000-8000-000000000001'::uuid, 'paused service history retains original assignment');
select pg_temp.check(not exists(select 1 from public.tasks t join connect_test_snapshots s on s.kind = 'task' and s.id = t.id where to_jsonb(t) is distinct from s.value), 'reconnecting preserves historical and current task fields');
insert into connect_test_calls select 'empty-template', r.* from public.connect_client_service('92000000-0000-4000-8000-000000000001', '97000000-0000-4000-8000-000000000001', '93000000-0000-4000-8000-000000000003', array['91000000-0000-4000-8000-000000000003']::uuid[]) r;
select pg_temp.check((select tasks_assigned = 0 and tasks_generated = 0 from connect_test_calls where name = 'empty-template'), 'service without defined deliverables can be connected without invented tasks');
select pg_temp.check((select default_configured and default_assignees = array['91000000-0000-4000-8000-000000000003']::uuid[] from public.service_assignment_options('92000000-0000-4000-8000-000000000001') where project_id = (select project_id from connect_test_calls where name = 'empty-template')), 'empty template still retains independent future team');

select pg_temp.reject('select public.connect_client_service(''92000000-0000-4000-8000-000000000001'',''97000000-0000-4000-8000-000000000004'',''93000000-0000-4000-8000-000000000002'',''{}''::uuid[])', '42501', 'foreign client rejected');
select pg_temp.reject('select public.connect_client_service(''92000000-0000-4000-8000-000000000001'',''97000000-0000-4000-8000-000000000001'',''93000000-0000-4000-8000-000000000004'',''{}''::uuid[])', '42501', 'foreign service template rejected');
select pg_temp.reject('select public.connect_client_service(''92000000-0000-4000-8000-000000000001'',''97000000-0000-4000-8000-000000000001'',''93000000-0000-4000-8000-000000000002'',array[''91000000-0000-4000-8000-000000000004'']::uuid[])', '23503', 'foreign workspace teammate rejected before link creation');
select pg_temp.check((select count(*) from public.projects where client_id = '97000000-0000-4000-8000-000000000001' and service_template_id = '93000000-0000-4000-8000-000000000002') = 0, 'failed connection leaves no partially created client service');
select pg_temp.reject('select public.connect_client_service(''92000000-0000-4000-8000-000000000001'',''97000000-0000-4000-8000-000000000001'',''93000000-0000-4000-8000-000000000002'',null)', '22023', 'null teammate list rejected');
select pg_temp.reject('select public.connect_client_service(''92000000-0000-4000-8000-000000000001'',''97000000-0000-4000-8000-000000000001'',''93000000-0000-4000-8000-000000000002'',array[null]::uuid[])', '22023', 'null teammate element rejected');
select pg_temp.reject('select public.connect_client_service(''92000000-0000-4000-8000-000000000001'',''97000000-0000-4000-8000-000000000001'',''93000000-0000-4000-8000-000000000002'',array_fill(''91000000-0000-4000-8000-000000000001''::uuid,array[101]))', '22023', 'teammate bound enforced');
select pg_temp.reject('select public.generate_service_deliverables(''92000000-0000-4000-8000-000000000002'',''95000000-0000-4000-8000-000000000001'')', '42501', 'cross tenant scoped generation rejected');
select pg_temp.check((select count(*) from public.tasks where project_id = '95000000-0000-4000-8000-000000000001') = 0, 'unrelated client still has no generated tasks after all operations');

select set_config('request.jwt.claim.sub', '91000000-0000-4000-8000-000000000003', true);
select pg_temp.reject('select public.connect_client_service(''92000000-0000-4000-8000-000000000001'',''97000000-0000-4000-8000-000000000001'',''93000000-0000-4000-8000-000000000002'',''{}''::uuid[])', '42501', 'ordinary member cannot connect client services');
select pg_temp.reject('select public.generate_service_deliverables(''92000000-0000-4000-8000-000000000001'',''95000000-0000-4000-8000-000000000001'')', '42501', 'ordinary member cannot invoke scoped generation');
select set_config('request.jwt.claim.sub', '91000000-0000-4000-8000-000000000004', true);
select pg_temp.reject('select public.connect_client_service(''92000000-0000-4000-8000-000000000001'',''97000000-0000-4000-8000-000000000001'',''93000000-0000-4000-8000-000000000002'',''{}''::uuid[])', '42501', 'outsider cannot connect another workspace services');
select set_config('request.jwt.claim.sub', '', true);
select pg_temp.reject('select public.connect_client_service(''92000000-0000-4000-8000-000000000001'',''97000000-0000-4000-8000-000000000001'',''93000000-0000-4000-8000-000000000002'',''{}''::uuid[])', '42501', 'authenticated role without user identity rejected');
select set_config('request.jwt.claim.sub', '91000000-0000-4000-8000-000000000002', true);
insert into connect_test_calls select 'admin-empty', r.* from public.connect_client_service('92000000-0000-4000-8000-000000000001', '97000000-0000-4000-8000-000000000001', '93000000-0000-4000-8000-000000000002', '{}'::uuid[]) r;
select pg_temp.check((select tasks_assigned = 1 and tasks_generated = 1 from connect_test_calls where name = 'admin-empty'), 'admin can connect existing service with deliberate empty team');
select pg_temp.check((select count(*) from public.task_assignees a join public.tasks t on t.id = a.task_id where t.project_id = (select project_id from connect_test_calls where name = 'admin-empty')) = 0, 'deliberately unassigned service generates unassigned work');
reset role;
grant select, insert on connect_test_results to anon;
set local role anon;
select pg_temp.reject('select public.connect_client_service(''92000000-0000-4000-8000-000000000001'',''97000000-0000-4000-8000-000000000001'',''93000000-0000-4000-8000-000000000002'',''{}''::uuid[])', '42501', 'anonymous caller cannot connect client services');
select pg_temp.reject('select public.generate_service_deliverables(''92000000-0000-4000-8000-000000000001'',''95000000-0000-4000-8000-000000000001'')', '42501', 'anonymous caller cannot invoke scoped generator');
reset role;
select count(*) as passed_checks, bool_and(passed) as all_passed from connect_test_results;
rollback;
